#!/usr/bin/env bash
# Installs and configures HAproxy on a new Ubuntu machine with roundrobin load balancing

apt-get update -y
apt-get install haproxy -y

echo "ENABLED=1" > /etc/default/haproxy

cat > /etc/haproxy/haproxy.cfg << 'HAPROXY'
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 7068-web-01 3.92.239.4:80 check
    server 7068-web-02 34.238.49.220:80 check
HAPROXY

service haproxy restart
