#!/usr/bin/env bash
# Installs and configures HAProxy on a new Ubuntu machine
# to distribute traffic to web-01 and web-02 using roundrobin

sudo apt-get update
sudo apt-get -y install haproxy

# Enable HAProxy to be managed via init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Configure HAProxy frontend and backend
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOF

frontend frontend_cluster
    bind *:80
    default_backend backend_cluster

backend backend_cluster
    balance roundrobin
    server 7068-web-01 3.92.239.4:80 check
    server 7068-web-02 34.238.49.180:80 check
EOF

sudo service haproxy restart
