#!/usr/bin/env bash
# Installs and configures nginx web server
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx restart
